### ISSUE TITLE
 Fit negative binomial offspring distribution

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/superspreading#1]
Add functionality to estimate R and k from individual-level transmission chain data (e.g. [Adam et al, 2020](https://www.nature.com/articles/s41591-020-1092-0). This functionality could also be integrated with `readepi` and `godataR` to allow direct estimation from imported timeseries. The values could also be passed to [`bpmodels`](https://github.com/sbfnk/bpmodels) to allow for simulation of branching process outbreaks from the estimated values.

**Comment by adamkucharski** [comment]
The fitting can be done with `fitdistrplus::fitdist()`, so main task will be data formatting for input/output (e.g. from contact datasets) to reduce need for manual standardisation

**Comment by joshwlambert** [comment]
@adamkucharski given, as you say above, that this functionality already exists in packages like {fitdistrplus} I wonder whether the best way to tackle this issue is with a vignette. It could be an elaboration on the example given in the readme? 

What do you think?

Thoughts on vignette structure could be:
1. Read in and tidy data
2. Fit negative binomial model with {fitdistrplus}
3. Apply summary metrics from {superspreading}
4. Simulate with {bpmodels} with negative binomial parameters

**Comment by adamkucharski** [comment]
I agree, that sounds like a good structure for a vignette.
